### ISSUE TITLE
 [vite] Internal server error: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by thisVioletHydra** [csstools/postcss-font-magician#108]
```ts
Cannot read properties of undefined (reading 'length')
08:51:38 [vite] Internal server error: Cannot read properties of undefined (reading 'length')
      at memoizedBinarySearch (file:///D:/WWW/sdfsddfsdfsdf/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:10022:25)
      at traceSegmentInternal (file:///D:/WWW/sdfsddfsdfsdf/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:10129:17)
      at originalPositionFor$1 (file:///D:/WWW/sdfsddfsdfsdf/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:10115:23)
      at formatError (file:///D:/WWW/sdfsddfsdfsdf/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:41297:54)
      at TransformContext.error (file:///D:/WWW/sdfsddfsdfsdf/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:41231:19)
      at Object.transform (file:///D:/WWW/sdfsddfsdfsdf/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:41509:25)
      at async loadAndTransform (file:///D:/WWW/sdfsddfsdfsdf/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:39313:29)
```
when i disable this config, vite start working:
```ts
'postcss-font-magician': {
    foundries: ['custom'],

    custom: customFontObject([
                  ^^^^^^^^^^^^^
      /**
       * filename - font name in project folder
       * cssName - font-family string in css
       */
      { filename: 'golos-text', cssName: 'local-golos-text' },
      // { filename: 'roboto', cssName: 'local-Roboto' },
    ]),

    display: 'swap',
    formats: 'woff2 woff',
    hosted: ['~~assets/fonts/'],
  },
```

customFontObject:
```ts
const genWoff = ({ genFile, genWeight }) => ({
  woff2: `~~assets/fonts/${genFile}-${genWeight}.woff2`,
  woff: `~~assets/fonts/${genFile}-${genWeight}.woff`,
});

const generate = ({ filename, cssName }) => {
  const obj = {
    400: 'regular',
    500: 'medium',
    600: 'semibold',
    700: 'bold',
    900: 'black',
  };

  const variables = Object.entries(obj);
  // const normal = {};

  // for (const [_key, _value] of variables) {
  //   normal[_key as keyof typeof obj] = {
  //     url: genWoff({ genFile: filename, genWeight: _value }),
  //   };
  // }

  const normal = variables.reduce((acc, [_key, _value]) => {
    acc[_key] = {
      url: genWoff({ genFile: filename, genWeight: _value }),
    };
    return acc;
  }, {});

  return { [cssName]: { variants: { normal } } };
};

module.exports = {
  customFontObject: (items) => {
    const result = Object.fromEntries(items.flatMap((f) => Object.entries(generate(f))));
    console.log(`[LOG] result`, `<${typeof result}>`, result);
    return result;
  },
};

```

console log :  
```q
{
  "[LOG] result <object>": {
    "local-golos-text": {
      "variants": {
        "normal": {
          "400": {
            "url": {
              "woff2": "~~assets/fonts/golos-text-regular.woff2",
              "woff": "~~assets/fonts/golos-text-regular.woff"
            }
          },
          "500": {
            "url": {
              "woff2": "~~assets/fonts/golos-text-medium.woff2",
              "woff": "~~assets/fonts/golos-text-medium.woff"
            }
          },
          "600": {
            "url": {
              "woff2": "~~assets/fonts/golos-text-semibold.woff2",
              "woff": "~~assets/fonts/golos-text-semibold.woff"
            }
          },
          "700": {
            "url": {
              "woff2": "~~assets/fonts/golos-text-bold.woff2",
              "woff": "~~assets/fonts/golos-text-bold.woff"
            }
          },
          "900": {
            "url": {
              "woff2": "~~assets/fonts/golos-text-black.woff2",
              "woff": "~~assets/fonts/golos-text-black.woff"
            }
          }
        }
      }
    }
  }
}


```

**Comment by romainmenke** [comment]
I can't help with Vite issues unless you provide a minimal repro.
Vite bundles and mangles dependencies so I can't even see from the stacktrace what is going on.

Closing for now, but happy to revisit if a GitHub repo is provided with a reproduction
